### ISSUE TITLE
INstagramy doesnt work on a hosted API

### ISSUE THREAD

**Issue by OmarSammanKaakajiDM** [yogeshwaran01/instagramy#28]
I am doing an API on flask that gets instagram hashtag posts. My problem is that when I run the flask application locally, it works fine. However when I host it on Azures web service or python anywhere, I keep on getting an internal server error. Has anyone faced this issue?

Error while using instagrammy:
```
2022-05-11 07:33:07,644: Exception on /api/instaposts [GET]
Traceback (most recent call last):
  File "/home/datamindsetstest/mysite/app.py", line 136, in api_posts
    hashtag = InstagramHashTag(word)
  File "/home/datamindsetstest/.local/lib/python3.9/site-packages/instagramy/InstagramHashTag.py", line 60, in __init__
    tag, data["entry_data"]["TagPage"][0]["graphql"]["hashtag"]
KeyError: 'TagPage'
```

**Comment by yogeshwaran01** [comment]
Yes It does not work on a server
